apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-test
  namespace: argocd
spec:
  project: guestbook
  source:
    repoURL: https://github.com/IAMDEH/argocd-test.git
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
   automated:
    prune: false
    selfHeal: false
