apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-ui
  namespace: argocd
spec:
  project: guestbook
  source:
    repoURL: https://github.com/IAMDEH/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
